rm -rf ./mempair.*
rm -rf ./mempair_all.*
rm -rf ./mssa.*
rm -rf ./ConConfig.*
rm -rf ./out_*
rm -rf ./in
rm -rf ./*.dot
rm -rf ./*.bc.r
rm -rf ./.*.o
rm -rf ./.*.o.bc
rm -rf ./*.out
rm -rf ./*.bc
rm -rf ./so.*
rm -rf ./mempairso.*
rm -rf ./dryRun.*
rm -rf ./*.log
rm -rf ./uaf
rm -rf ./*.uaf
rm -rf ./*.xml
rm -rf ./*.ll
rm -rf ./dbds.*
rm -rf ./*.o
rm -rf ./*.npy
rm -rf ./*.txt
rm -rf ./*.npz
rm -rf dot-files
rm -rf ./func_level_action.*
rm -f ./Group*
